name: "Check if last commit was deployed to pre with success"

on:
  pull_request:
    types: [closed]

jobs:
  find-last-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Get last commit before merge
      if: github.event.pull_request.merged == true
      run: |
        echo "Merge commit: ${{ github.event.pull_request.merge_commit_sha }}
        MERGE_COMMIT=${{ github.event.pull_request.merge_commit_sha }}
        LAST_COMMIT_BEFORE_MERGE=$(git log -n 1 ${MERGE_COMMIT}^2 --format="%H")
        echo $LAST_COMMIT_BEFORE_MERGE