name: "Check if last commit was deployed to pre with success"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  find-last-commit:
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: check current commit
      if: github.event.pull_request.merged == false
      run: |
        echo "last commit in the branch is: ${{ github.event.pull_request.head.sha }}"

    - name: Get last commit before merge
      if: github.event.pull_request.merged == true
      run: |
        echo "Last branch commit: ${{ github.event.pull_request.head.sha }}"
