name: "Check if last commit was deployed to pre with success"

on:
  pull_request:
    types: [closed]

jobs:
  find-last-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"


    - name: Get last commit before merge
      if: github.event.pull_request.merged == true
      run: |
        echo "Last branch commit: ${{ github.event.pull_request.head.sha }}"
